### ISSUE TITLE
Cannot decode my PDF files though the sample one is fine

### ISSUE THREAD

**Issue by MandyShaw** [cpierce/pdf2text#1]
I cannot get any decoded text out of either of these:
[148154.pdf](https://github.com/cpierce/pdf2text/files/7877397/148154.pdf)
[temp.pdf](https://github.com/cpierce/pdf2text/files/7877398/temp.pdf)

Your sample pdf works fine however.

It may be that I need to set an option to handle these files but I cannot work out what is needed so would appreciate help.

Here is my code (v simple):
`<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
require_once('Pdf2text.php');
function pdftotext($from) {
$pdf2text = new \Pdf2text\Pdf2text($from);
$output = $pdf2text->decode();
var_dump($output);
}
?>
`
Thank you
Mandy Shaw

**Comment by cpierce** [comment]
I believe the problem is that your files aren't OCR'ed ... the script simply reads the OCR information out of the file and all of your stuff is just images ... open adobe on the temp.pdf and run it through an OCR and the following results happen:

```string(161) "Set in D minorGottfried Finger?1655 - 1730
notAmos Performing Editions1 Lansdown Place EastBathBA1 5ETUnited Kingdomwww.notAmos.co.ukScore number 147042notAmos
"```
